from PyQt5 import QtCore, QtGui, QtWidgets


class OpenCamUi(object):
    def setup_ui(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(694, 800)
        self.container = QtWidgets.QWidget(main_window)
        self.container.setObjectName("container")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.container)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mainBox = QtWidgets.QVBoxLayout()
        self.mainBox.setObjectName("mainBox")
        self.topBox = QtWidgets.QHBoxLayout()
        self.topBox.setContentsMargins(-1, 0, 0, -1)
        self.topBox.setObjectName("topBox")
        self.camBtn_open = QtWidgets.QPushButton(self.container)
        self.camBtn_open.setEnabled(True)
        self.camBtn_open.setMinimumSize(QtCore.QSize(100, 40))
        self.camBtn_open.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.camBtn_open.setFont(font)
        self.camBtn_open.setIconSize(QtCore.QSize(20, 20))
        self.camBtn_open.setCheckable(False)
        self.camBtn_open.setObjectName("camBtn_open")
        self.topBox.addWidget(self.camBtn_open)
        self.camBtn_stop = QtWidgets.QPushButton(self.container)
        self.camBtn_stop.setEnabled(True)
        self.camBtn_stop.setMinimumSize(QtCore.QSize(100, 40))
        self.camBtn_stop.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.camBtn_stop.setFont(font)
        self.camBtn_stop.setObjectName("camBtn_stop")
        self.topBox.addWidget(self.camBtn_stop)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.topBox.addItem(spacerItem)
        self.mainBox.addLayout(self.topBox)
        self.midBox = QtWidgets.QHBoxLayout()
        self.midBox.setObjectName("midBox")
        self.view = QtWidgets.QScrollArea(self.container)
        self.view.setMinimumSize(QtCore.QSize(670, 670))
        self.view.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.view.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.view.setWidgetResizable(True)
        self.view.setObjectName("view")
        self.viewForm = QtWidgets.QWidget()
        self.viewForm.setGeometry(QtCore.QRect(0, 0, 653, 653))
        self.viewForm.setObjectName("viewForm")
        self.viewData = QtWidgets.QLabel(self.viewForm)
        self.viewData.setGeometry(QtCore.QRect(0, 0, 650, 650))
        self.viewData.setMinimumSize(QtCore.QSize(650, 650))
        self.viewData.setMaximumSize(QtCore.QSize(650, 650))
        self.viewData.setText("")
        self.viewData.setObjectName("viewData")
        self.view.setWidget(self.viewForm)
        self.midBox.addWidget(self.view)
        self.mainBox.addLayout(self.midBox)
        self.bottomBox = QtWidgets.QHBoxLayout()
        self.bottomBox.setObjectName("bottomBox")
        self.viewCbo_roi = QtWidgets.QComboBox(self.container)
        self.viewCbo_roi.setMinimumSize(QtCore.QSize(80, 26))
        self.viewCbo_roi.setMaximumSize(QtCore.QSize(80, 26))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.viewCbo_roi.setFont(font)
        self.viewCbo_roi.setMaxVisibleItems(10)
        self.viewCbo_roi.setObjectName("viewCbo_roi")
        self.viewCbo_roi.addItem("")
        self.viewCbo_roi.addItem("")
        self.viewCbo_roi.addItem("")
        self.viewCbo_roi.addItem("")
        self.viewCbo_roi.addItem("")
        self.bottomBox.addWidget(self.viewCbo_roi)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bottomBox.addItem(spacerItem1)
        self.mainBox.addLayout(self.bottomBox)
        self.horizontalLayout_2.addLayout(self.mainBox)
        main_window.setCentralWidget(self.container)
        self.statusBar = QtWidgets.QStatusBar(main_window)
        self.statusBar.setObjectName("statusBar")
        main_window.setStatusBar(self.statusBar)
        self.actionOpen = QtWidgets.QAction(main_window)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(main_window)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(main_window)
        self.actionSave_As.setObjectName("actionSave_As")

        self.retranslate_ui(main_window)
        self.viewCbo_roi.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslate_ui(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "WebCam"))
        self.camBtn_open.setText(_translate("main_window", "Open"))
        self.camBtn_stop.setText(_translate("main_window", "Stop"))
        self.viewCbo_roi.setItemText(0, _translate("main_window", "0.50"))
        self.viewCbo_roi.setItemText(1, _translate("main_window", "0.75"))
        self.viewCbo_roi.setItemText(2, _translate("main_window", "1.00"))
        self.viewCbo_roi.setItemText(3, _translate("main_window", "1.25"))
        self.viewCbo_roi.setItemText(4, _translate("main_window", "1.50"))
        self.actionOpen.setText(_translate("main_window", "Open"))
        self.actionSave.setText(_translate("main_window", "Save"))
        self.actionSave_As.setText(_translate("main_window", "Save As"))
